In [2]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import PolynomialFeatures, StandardScaler, RobustScaler, OrdinalEncoder
from sklearn.linear_model import LinearRegression, SGDClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.feature_selection import f_regression, SelectKBest, VarianceThreshold, SelectKBest
import statsmodels.api as sm
from pandas import to_datetime
from pycaret.regression import *
from datetime import datetime
from test_functions import *

In [16]:
test = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/flights_TEST.txt')

In [17]:
test['fl_date'] = pd.to_datetime(test['year'].astype(str) + '-' + test['month'].astype(str) + '-' + test['day'].astype(str))

In [18]:
test = test[test['day'] < 8]

In [19]:
test = process_times(test)
test = combine_tail_num_avg(dec, test)
test = combine_carriers(dec, test)
test = combine_weekly(dec, test)
test = combine_hourly(dec, test)
test = combine_routes(dec, test)
test = airport_combine_test(dec, test)
test.columns

Index(['year', 'month', 'day', 'op_unique_carrier', 'tail_num',
       'origin_airport_id', 'dest_airport_id', 'crs_dep_time', 'crs_arr_time',
       'crs_elapsed_time', 'fl_date', 'dep_hour', 'arr_hour', 'weekday',
       'month_day', 'tail_arr', 'tail_dep', 'tail_taxi', 'tail_precent_late',
       'tail_percent_reduce_delay', 'carrier_arr', 'carrier_dep',
       'carrier_percent_late', 'carrier_taxi_total',
       'percent_carrier_delay_reduced', 'weekday_arr', 'weekday_dep',
       'weekday_taxi', 'weekly_percent_late', 'weekly_reduced_delay',
       'arr_hourly_arr', 'arr_hourly_dep', 'arr_hour_taxi',
       'arr_hourly_percent_late', 'arr_hourly_percent_reduced_delay',
       'dep_hourly_arr', 'dep_hourly_dep', 'dep_hourly_taxi',
       'dep_hourly_percent_late', 'dep_hourly_percent_reduced',
       'route_arr_mean', 'route_dep_mean', 'carrier_route_arr_mean',
       'carrier_route_dep_mean', 'carrier_route_air_percent',
       'tail_route_arr_mean', 'tail_route_dep_mean', 'tail_route_air_ratio',
       'airport_weekly_hourly_arr', 'airport_weekly_hourly_dep',
       'airport_arr_hourly_late_percent', 'airport_dep_hourly_late_percent',
       'airport_taxi_in', 'airport_taxi_out'],
      dtype='object')

In [11]:
test = test.drop(columns=['fl_date', 'crs_dep_time', 'crs_arr_time', 'month', 'day', 'year'])

In [3]:
df = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/test3.csv')

In [5]:
big = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/random_sample.txt')

In [14]:
dec = dec[dec['month_day'] > 14]

In [4]:
from EDA_and_preprocessing.functions import *
dec = remove_outliers(dec)
dec = process_times(dec)
dec = process_binary(dec)
dec = airport_hour_avgs(dec)
dec = tail_num_avg(dec)
dec = process_carriers(dec)
dec = process_hourly(dec)
dec = process_weekly(dec)
dec = process_routes(dec)

In [21]:
X_test = test.drop(columns=['fl_date', 'op_unique_carrier', 'tail_num', 'origin_airport_id','dest_airport_id', 'crs_dep_time', 'crs_arr_time', 'weekday', 'month_day', 'month', 'day', 'year'])

In [20]:
X = dec.drop(columns=['fl_date', 'op_unique_carrier', 'tail_num', 'origin_airport_id','dest_airport_id', 'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out','taxi_in', 'crs_arr_time', 'carrier_route_air_actual', 'carrier_route_air_pred', 'arr_time', 'actual_elapsed_time','weekday', 'month_day','late_binary', 'reduced_delay_flight','taxi_total'])

In [22]:
X_test = test
cols = X.drop(columns='arr_delay').columns
cols = cols
X_test = X_test[cols]

In [23]:
from pycaret.regression import *
exp1 = setup(data=X,target='arr_delay', ignore_low_variance=False, combine_rare_levels=True, feature_interaction=False, feature_selection=False, feature_selection_threshold=0.6, feature_ratio=False, polynomial_features=False, remove_outliers=True, remove_multicollinearity=True, transformation=True, fold=4)

In [29]:
lightdec = create_model('lightgbm', fold=2)

In [30]:
light_tuned = tune_model(lightdec, fold=2, n_iter=10, choose_better=True, return_tuner=True, return_train_score=True)

In [19]:
cols = X.drop(columns='arr_delay').columns
X_test = X_test[cols]

In [117]:
evaluate_model(light1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [40]:
evaluate_model(light1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [15]:
X_test = get_config('X_test')

In [16]:
best = compare_models()

In [18]:
light1 = finalize_model(light1)

In [25]:
y_pred = predict_model(light1, data=X_test)

In [115]:
import xgboost

In [24]:
xgboost = create_model('xgboost')

In [1]:
print(X.columns, X_test.columns)

NameError: name 'X' is not defined

In [65]:
big = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/new flights.txt')

In [15]:
print(dec.isnull().sum(), dec.nunique())

fl_date                            0
op_unique_carrier                  0
tail_num                           0
origin_airport_id                  0
dest_airport_id                    0
crs_dep_time                       0
dep_time                           0
dep_delay                          0
taxi_out                           0
taxi_in                            0
crs_arr_time                       0
arr_time                           0
arr_delay                          0
crs_elapsed_time                   0
actual_elapsed_time                0
dep_hour                           0
arr_hour                           0
weekday                            0
month_day                          0
late_binary                        0
reduced_delay_flight               0
airport_weekly_hourly_arr          0
airport_weekly_hourly_dep          0
airport_arr_hourly_late_percent    0
airport_dep_hourly_late_percent    0
airport_taxi_in                    0
airport_taxi_out                   0
taxi_total                         0
tail_arr                           0
tail_dep                           0
tail_taxi                          0
tail_precent_late                  0
tail_percent_reduce_delay          0
carrier_arr                        0
carrier_dep                        0
carrier_percent_late               0
carrier_taxi_total                 0
percent_carrier_delay_reduced      0
weekday_arr                        0
weekday_dep                        0
weekday_taxi                       0
weekly_percent_late                0
weekly_reduced_delay               0
route_arr_mean                     0
route_dep_mean                     0
carrier_route_arr_mean             0
carrier_route_dep_mean             0
carrier_route_air_actual           0
carrier_route_air_pred             0
tail_route_arr_mean                0
tail_route_dep_mean                0
tail_route_air_ratio               0
dtype: int64 fl_date                               31
op_unique_carrier                     25
tail_num                            5515
origin_airport_id                    363
dest_airport_id                      363
crs_dep_time                        1261
dep_time                            1432
dep_delay                            191
taxi_out                             140
taxi_in                              115
crs_arr_time                        1394
arr_time                            1440
arr_delay                            149
crs_elapsed_time                     422
actual_elapsed_time                  483
dep_hour                              24
arr_hour                              24
weekday                                7
month_day                             31
late_binary                            2
reduced_delay_flight                   2
airport_weekly_hourly_arr           8123
airport_weekly_hourly_dep           7658
airport_arr_hourly_late_percent     1735
airport_dep_hourly_late_percent     1685
airport_taxi_in                      361
airport_taxi_out                     363
taxi_total                           147
tail_arr                            5201
tail_dep                            5183
tail_taxi                           5106
tail_precent_late                   2376
tail_percent_reduce_delay           2242
carrier_arr                           25
carrier_dep                           25
carrier_percent_late                  25
carrier_taxi_total                    25
percent_carrier_delay_reduced         25
weekday_arr                            7
weekday_dep                            7
weekday_taxi                           7
weekly_percent_late                    7
weekly_reduced_delay                   7
route_arr_mean                      5186
route_dep_mean                      5019
carrier_route_arr_mean              8203
carrier_route_dep_mean              7733
carrier_route_air_actual           10087
carrier_route_air_pred              9265
tail_route_arr_mean                 2230
tail_route_dep_mean                 1993
tail_route_air_ratio               41087
dtype: int64

In [13]:
print(test.isnull().sum(), test.nunique())

year                                    0
month                                   0
day                                     0
op_unique_carrier                       0
tail_num                              124
origin_airport_id                       0
dest_airport_id                         0
crs_dep_time                            0
crs_arr_time                            0
crs_elapsed_time                        0
fl_date                                 0
dep_hour                               17
arr_hour                              514
weekday                                 0
month_day                               0
tail_arr                              538
tail_dep                              538
tail_taxi                             538
tail_precent_late                     538
tail_percent_reduce_delay             538
carrier_arr                             0
carrier_dep                             0
carrier_percent_late                    0
carrier_taxi_total                      0
percent_carrier_delay_reduced           0
weekday_arr                             0
weekday_dep                             0
weekday_taxi                            0
weekly_percent_late                     0
weekly_reduced_delay                    0
arr_hourly_arr                        514
arr_hourly_dep                        514
arr_hour_taxi                         514
arr_hourly_percent_late               514
arr_hourly_percent_reduced_delay      514
dep_hourly_arr                         17
dep_hourly_dep                         17
dep_hourly_taxi                        17
dep_hourly_percent_late                17
dep_hourly_percent_reduced             17
route_arr_mean                        195
route_dep_mean                        195
carrier_route_arr_mean                724
carrier_route_dep_mean                724
carrier_route_air_percent             724
tail_route_arr_mean                 77083
tail_route_dep_mean                 77083
tail_route_air_ratio                77083
airport_weekly_hourly_arr            1007
airport_weekly_hourly_dep             434
airport_arr_hourly_late_percent       669
airport_dep_hourly_late_percent       191
airport_taxi_in                         0
airport_taxi_out                        0
dtype: int64 year                                    1
month                                   1
day                                     7
op_unique_carrier                      25
tail_num                             5556
origin_airport_id                     363
dest_airport_id                       363
crs_dep_time                         1229
crs_arr_time                         1311
crs_elapsed_time                      454
fl_date                                 7
dep_hour                               24
arr_hour                               24
weekday                                 7
month_day                               7
tail_arr                             5201
tail_dep                             5183
tail_taxi                            5106
tail_precent_late                    2376
tail_percent_reduce_delay            2242
carrier_arr                            25
carrier_dep                            25
carrier_percent_late                   25
carrier_taxi_total                     25
percent_carrier_delay_reduced          25
weekday_arr                             7
weekday_dep                             7
weekday_taxi                            7
weekly_percent_late                     7
weekly_reduced_delay                    7
arr_hourly_arr                         24
arr_hourly_dep                         24
arr_hour_taxi                          24
arr_hourly_percent_late                24
arr_hourly_percent_reduced_delay       24
dep_hourly_arr                         24
dep_hourly_dep                         24
dep_hourly_taxi                        24
dep_hourly_percent_late                24
dep_hourly_percent_reduced             24
route_arr_mean                       5163
route_dep_mean                       5004
carrier_route_arr_mean               7989
carrier_route_dep_mean               7554
carrier_route_air_percent           10623
tail_route_arr_mean                  1840
tail_route_dep_mean                  1640
tail_route_air_ratio                19678
airport_weekly_hourly_arr            8044
airport_weekly_hourly_dep            7589
airport_arr_hourly_late_percent      1731
airport_dep_hourly_late_percent      1665
airport_taxi_in                       361
airport_taxi_out                      363
dtype: int64

In [3]:
dec = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/december_flights.txt')

In [109]:
set(X.drop(columns='arr_delay').columns) == set(X_test.columns)

True

In [119]:
save_model(light1, 'lgbm_all_december')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[], target='arr_delay',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strate...
                  LGBMRegressor(boosting_type='gbdt', class_weight=None,
                                colsample_bytree=1.0, importance_type='split',
                                learning_rate=0.1, max_depth=-1,
                                min_child_samples=20, min_child_weight=0.001,
                                min_split_gain=0.0, n_estimators=100, n_jobs=-1,
                                num_leaves=31, objective=None, random_state=5418,
                                reg_alpha=0.0, reg_lambda=0.0, silent='warn',
                                subsample=1.0, subsample_for_bin=200000,
                                subsample_freq=0)]],
          verbose=False),
 'lgbm_all_december.pkl')

In [18]:
set(test['tail_num']) - set(dec['tail_num'])

{'N106NN',
 'N11113',
 'N12010',
 'N166PQ',
 'N16713',
 'N18243',
 'N2027J',
 'N227JQ',
 'N2748U',
 'N289MW',
 'N36915',
 'N38443',
 'N38950',
 'N391DN',
 'N426AW',
 'N504DN',
 'N511DN',
 'N554GJ',
 'N582CA',
 'N618UX',
 'N619UX',
 'N668UA',
 'N670UA',
 'N672UA',
 'N677UA',
 'N702DN',
 'N727TW',
 'N753AN',
 'N78017',
 'N7821L',
 'N7849A',
 'N7866A',
 'N7867A',
 'N786UA',
 'N798UA',
 'N801UA',
 'N804HC',
 'N804NW',
 'N839MH',
 'N8932C',
 'N8968E',
 nan}

In [31]:
air_traffic = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/air_traffic_binned.csv')
airline_delay = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/airline_delay_rating.csv')
weather_test = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/weather_test.csv')
weather_train = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/weather_train.csv')

In [32]:
pred = pd.read_csv('prediction.csv')

In [34]:
p = pd.read_csv('EDA_and_preprocessing/G_PSQL_data/final_flight_test.csv')

In [35]:
p

,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,...,tail_route_air_ratio,airport_weekly_hourly_arr,airport_weekly_hourly_dep,airport_arr_hourly_late_percent,airport_dep_hourly_late_percent,airport_taxi_in,airport_taxi_out,dist_times,tail_dist_dep,tail_dist_arr
0,0,2020-01-01,WN,WN,WN,5888,WN,N951WN,5888,13891,...,NaN,27.162791,1.200000,36.790123,45.238095,9.368642,13.249526,short,7.203704,1.351852
1,1,2020-01-01,WN,WN,WN,6276,WN,N467WN,6276,13891,...,NaN,25.033333,5.600000,37.086093,51.351351,9.368642,13.249526,short,8.432432,3.405405
2,2,2020-01-01,WN,WN,WN,4598,WN,N7885A,4598,13891,...,NaN,5.388889,3.285714,40.740741,50.000000,4.739518,13.249526,short,3.200000,-6.200000
3,3,2020-01-01,WN,WN,WN,4761,WN,N551WN,4761,13891,...,86.666667,-8.714286,6.250000,26.595745,41.176471,4.739518,13.249526,short,7.954545,1.545455
4,4,2020-01-01,WN,WN,WN,5162,WN,N968WN,5162,13891,...,NaN,-10.190476,22.800000,16.216216,36.111111,4.739518,13.249526,short,20.352941,8.294118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150618,150618,2020-01-07,UA,UA,UA,213,UA,N587UA,213,14771,...,102.649380,5.600000,14.500000,37.142857,47.420147,12.751628,20.655905,long,2.222222,-2.472222
150619,150619,2020-01-07,UA,UA,UA,212,UA,N810UA,212,13303,...,NaN,0.286550,0.745763,32.822086,24.169184,6.081383,18.956483,medium,3.037037,-6.296296
150620,150620,2020-01-07,UA,UA,UA,212,UA,N810UA,212,13930,...,108.152174,-7.515152,9.406015,31.506849,36.633663,8.409209,22.706989,long,-1.714286,-9.392857
150621,150621,2020-01-07,UA,UA,UA,210,UA,N77536,210,10423,...,NaN,9.687500,2.333333,47.560976,32.417582,12.751628,13.472374,long,0.733333,-14.066667
150622,150622,2020-01-07,UA,UA,UA,209,UA,N76265,209,14908,...,NaN,-10.050847,-4.257143,30.963665,32.019704,9.368642,14.464004,short,-2.125000,-6.250000

In [36]:
pred

,Unnamed: 0,mkt_carrier_fl_num,crs_elapsed_time,dep_hour,arr_hour,dest_weather,airline_delay_category,total_flights,flight_bins,airport_weekly_hourly_arr,...,weekly_reduced_delay,route_arr_mean,route_dep_mean,carrier_route_arr_mean,carrier_route_dep_mean,carrier_route_air_percent,dist_times,tail_dist_dep,tail_dist_arr,Label
0,0,5888,95,18.0,20.0,1.0,3.0,3096,5,27.162791,...,76.887272,2.672566,12.238938,8.238095,18.690476,87.805556,short,7.203704,1.351852,15.619381
1,1,6276,90,12.0,13.0,1.0,3.0,3096,5,25.033333,...,76.887272,2.672566,12.238938,8.238095,18.690476,87.805556,short,8.432432,3.405405,17.038452
2,2,4598,70,20.0,22.0,1.0,3.0,3096,5,5.388889,...,76.887272,4.736111,9.750000,4.736111,9.750000,93.143400,short,3.200000,-6.200000,-3.441783
3,3,4761,75,14.0,15.0,1.0,3.0,3096,5,-8.714286,...,76.887272,4.736111,9.750000,4.736111,9.750000,93.143400,short,7.954545,1.545455,-6.578942
4,4,5162,80,9.0,11.0,1.0,3.0,3096,5,-10.190476,...,76.887272,4.736111,9.750000,4.736111,9.750000,93.143400,short,20.352941,8.294118,13.331636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150618,150618,213,317,16.0,3.0,1.0,3.0,21784,5,5.600000,...,74.132218,8.092920,7.079646,9.167598,6.994413,100.683475,long,2.222222,-2.472222,9.066453
150619,150619,212,150,14.0,16.0,3.0,3.0,13139,5,0.286550,...,74.132218,-4.357143,-0.250000,-4.357143,-0.250000,97.274882,medium,3.037037,-6.296296,-3.379348
150620,150620,212,193,9.0,13.0,1.0,3.0,48662,5,-7.515152,...,74.132218,1.633929,5.004464,1.616667,3.833333,98.812712,long,-1.714286,-9.392857,-7.756240
150621,150621,210,217,17.0,22.0,1.0,3.0,8395,5,9.687500,...,74.132218,10.038462,11.173077,6.951220,9.195122,98.931227,long,0.733333,-14.066667,-4.312589
150622,150622,209,90,8.0,10.0,2.0,3.0,5488,5,-10.050847,...,74.132218,0.792553,4.973404,-2.250000,0.482143,97.153488,short,-2.125000,-6.250000,-9.956194

In [37]:
sample = pd.read_csv('sample_submission.csv')
cols = sample.drop(columns='predicted_delay').columns

In [39]:
p = p[cols]
p['predicted_delay'] = pred['Label']

In [41]:
p.to_csv('prediction.csv')

In [42]:
p

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,predicted_delay
0,2020-01-01,WN,5888,ONT,SFO,15.619381
1,2020-01-01,WN,6276,ONT,SFO,17.038452
2,2020-01-01,WN,4598,ONT,SJC,-3.441783
3,2020-01-01,WN,4761,ONT,SJC,-6.578942
4,2020-01-01,WN,5162,ONT,SJC,13.331636
...,...,...,...,...,...,...
150618,2020-01-07,UA,213,SFO,EWR,9.066453
150619,2020-01-07,UA,212,MIA,IAD,-3.379348
150620,2020-01-07,UA,212,ORD,MIA,-7.756240
150621,2020-01-07,UA,210,AUS,EWR,-4.312589
150622,2020-01-07,UA,209,SNA,SFO,-9.956194